/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.yourorghere;

import com.sun.opengl.util.Animator;
import javafx.concurrent.Task;

/**
 *
 * @author deivi
 */
public class CargaEscenario extends javax.swing.JFrame
{

    int personaje;
    int nivel;
    static int i;
    private final Animator per;

    /**
     * Creates new form CargaEscenario
     *
     * @param personaje
     * @param nivel
     */
    public CargaEscenario(int personaje, int nivel)
    {
        initComponents();
        this.personaje = personaje;
        switch (personaje)
        {
            case 1:
                SnowMan sm = new SnowMan(personaje, nivel);
                gLCanvas2.addGLEventListener(sm);
                break;
            case 2:
                SnowGirl sg = new SnowGirl(personaje, nivel);
                gLCanvas2.addGLEventListener(sg);
                break;
            case 3:
                MCowboy mc = new MCowboy(personaje, nivel);
                gLCanvas2.addGLEventListener(mc);
                break;
        }

        per = new Animator(gLCanvas2);
        per.start();

        setVisible(true);
        setSize(960, 550);
        //Generamos al centro de la pantalla con null
        setLocationRelativeTo(null);
        System.out.println("Cargando...");
        System.out.println("Personaje seleccionado: " + personaje);
        System.out.println("Nivel seleccionado: " + nivel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gLCanvas2 = new javax.media.opengl.GLCanvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gLCanvas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gLCanvas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CargaEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CargaEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CargaEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CargaEscenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CargaEscenario(0, 0).setVisible(true);

            }

        });

        /*
         Para implementar la progress bar es necesario que 
         al momento de arrastrar a nuestro JFrame, entremos 
         a las propiedades de la progress bar, y en Code, vamos a Variable Modifiers
         y ponerla como Public Static.
         De lo contrario no se podra mandar llamar en el ciclo de carga
         */
//        try
//        {
//            for (i = 1; i <= 100; i++)
//            {
//                Thread.sleep(50);
//                /*
//                 Si queremos mostrar en texto el porcentaje de carga
//                 usamos la linea comentada de abajo.
//                 */
//                //CargaEscenario.barra.setToolTipText(Integer.toString(i) + "%");
//                CargaEscenario.barra.setValue(i);
//            }
//
//        } catch (Exception e)
//        {
//            System.out.println("Error: " + e);
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.media.opengl.GLCanvas gLCanvas2;
    // End of variables declaration//GEN-END:variables
}
