/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.yourorghere;

/**
 *
 * @author deivi
 */
public class Niveles extends javax.swing.JFrame
{

    int personaje;

    /**
     * Creates new form Niveles
     */
    public Niveles(int personaje)
    {
        initComponents();
        this.personaje = personaje;
        System.out.println("Personaje numero: " + personaje + " seleccionado!");
    }

    /**
     * @return the personaje
     */
    public int getPersonaje()
    {
        return personaje;
    }

    /**
     * @param personaje the personaje to set
     */
//    public int setPersonaje(int personaje)
//    {
//        this.personaje = personaje;
//         return personaje;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        nivel2 = new javax.swing.JButton();
        nivel3 = new javax.swing.JButton();
        nivel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecciona un nivel");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel1.setText("Selecciona un nivel");

        nivel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura3.jpg"))); // NOI18N
        nivel2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nivel2ActionPerformed(evt);
            }
        });

        nivel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura3.jpg"))); // NOI18N
        nivel3.setEnabled(false);
        nivel3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nivel3ActionPerformed(evt);
            }
        });

        nivel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nivel1.png"))); // NOI18N
        nivel1.setToolTipText("");
        nivel1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nivel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(nivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nivel2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nivel2ActionPerformed
    {//GEN-HEADEREND:event_nivel2ActionPerformed
        // TODO add your handling code here:
        //CargaEscenario c = new CargaEscenario(personaje, 2);
        System.out.println("Nivel 2 seleccionado");
        GLRenderer glr = new GLRenderer();
        glr.main(2);
        //c.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_nivel2ActionPerformed

    private void nivel1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nivel1ActionPerformed
    {//GEN-HEADEREND:event_nivel1ActionPerformed
        // TODO add your handling code here:
        //CargaEscenario c = new CargaEscenario(personaje, 1);
        //   CargaEscenario c = new CargaEscenario(personaje, 1);
        System.out.println("Nivel 1 seleccionado");
        GLRenderer glr = new GLRenderer();
        glr.main(1);
//        c.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_nivel1ActionPerformed

    private void nivel3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nivel3ActionPerformed
    {//GEN-HEADEREND:event_nivel3ActionPerformed
        // TODO add your handling code here:
        System.out.println("Nivel 3 seleccionado");
        GLRenderer glr = new GLRenderer();
        glr.main(3);
        // CargaEscenario c = new CargaEscenario(personaje, 3);
        //c.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_nivel3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Niveles(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nivel1;
    private javax.swing.JButton nivel2;
    private javax.swing.JButton nivel3;
    // End of variables declaration//GEN-END:variables

}
